@echo off
echo Checking SQL Server versions > version.txt
echo -------------------------------------------------------- >> version.txt

REM Execute sqlcmd for each server with proper termination
echo Checking MPRW114...
sqlcmd -S MPRW114 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 -o version.txt

echo Checking MPRW115...
sqlcmd -S MPRW115 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW052...
sqlcmd -S SPRW052 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW053...
sqlcmd -S SPRW053 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking JPRW015...
sqlcmd -S JPRW015 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking JPRW016...
sqlcmd -S JPRW016 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW008...
sqlcmd -S SPRW008 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW132...
sqlcmd -S MPRW132 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SDEW032...
sqlcmd -S SDEW032 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SDEW033...
sqlcmd -S SDEW033 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW227...
sqlcmd -S MPRW227 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW228...
sqlcmd -S MPRW228 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW082...
sqlcmd -S SPRW082 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW083...
sqlcmd -S SPRW083 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW266...
sqlcmd -S MPRW266 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW265...
sqlcmd -S MPRW265 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW086...
sqlcmd -S SPRW086 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW085...
sqlcmd -S SPRW085 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking BDRW011...
sqlcmd -S BDRW011 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking BDRW016...
sqlcmd -S BDRW016 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPPW030...
sqlcmd -S SPPW030 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPPW055...
sqlcmd -S SPPW055 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW066...
sqlcmd -S MPRW066 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW067...
sqlcmd -S MPRW067 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking MPRW105...
sqlcmd -S MPRW105 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW026...
sqlcmd -S SPRW026 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SPRW027...
sqlcmd -S SPRW027 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking JUCCEAW1...
sqlcmd -S JUCCEAW1 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking JUCCEAW2...
sqlcmd -S JUCCEAW2 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking DUCCEAW1...
sqlcmd -S DUCCEAW1 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking DUCCEAW2...
sqlcmd -S DUCCEAW2 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking JUCCELGRA...
sqlcmd -S JUCCELGRA -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking DUCCELGRB...
sqlcmd -S DUCCELGRB -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking TESTSQL2012...
sqlcmd -S TESTSQL2012 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SCCM-SQL-TEMP...
sqlcmd -S SCCM-SQL-TEMP -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-006-CC-002...
sqlcmd -S RUH-006-CC-002 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-006-CC-001...
sqlcmd -S RUH-006-CC-001 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-002-CNS-103...
sqlcmd -S RUH-002-CNS-103 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-002-MIS-001...
sqlcmd -S RUH-002-MIS-001 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-002-RET-001...
sqlcmd -S RUH-002-RET-001 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-006-NCR-003...
sqlcmd -S RUH-006-NCR-003 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-002-NUD-101...
sqlcmd -S RUH-002-NUD-101 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-002-TOL-001...
sqlcmd -S RUH-002-TOL-001 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-006-DB-001...
sqlcmd -S RUH-006-DB-001 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-002-PMP-108...
sqlcmd -S RUH-002-PMP-108 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking RUH-002-PMP-109...
sqlcmd -S RUH-002-PMP-109 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking EECSARUH6HOW043...
sqlcmd -S EECSARUH6HOW043 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking EECSARUH6HOW156...
sqlcmd -S EECSARUH6HOW156 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking EECSARUH6HOW157...
sqlcmd -S EECSARUH6HOW157 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking EECSARUH2HOW885...
sqlcmd -S EECSARUH2HOW885 -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Checking SLBW010.CHILD.LAB.LAN...
sqlcmd -S SLBW010.CHILD.LAB.LAN -Q "SET NOCOUNT ON; SELECT @@SERVERNAME,@@VERSION;" -h-1 >> version.txt

echo Done! Results saved to version.txt