sqlcmd -E -i .\ServerDetails.sql -o .\Results\result34.csv  -m 1 		-s "," -W -f 65001 -S OPENTEXTPROD\OPENTEXTPROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result1.csv 	-m 1 -h-1 -s "," -W -f 65001 -S EGASSPCI
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result3.csv   -m 1 -h-1 -s "," -W -f 65001 -S EGA-SP-QDB1\IHUB_PROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result4.csv   -m 1 -h-1 -s "," -W -f 65001 -S EGA-SP-QDB1\GRA_PROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result5.csv   -m 1 -h-1 -s "," -W -f 65001 -S APPSCAN16N\APPSCAN
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result6.csv   -m 1 -h-1 -s "," -W -f 65001 -S AVAYACALLBILLN\AVAYACALLBILL
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result7.csv   -m 1 -h-1 -s "," -W -f 65001 -S BawbatiN\BAWBATI
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result8.csv   -m 1 -h-1 -s "," -W -f 65001 -S EstibyanN\ESTIBYAN
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result9.csv   -m 1 -h-1 -s "," -W -f 65001 -S GOANYWHEREN\GOANYWHERE
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result10.csv  -m 1 -h-1 -s "," -W -f 65001 -S Kofax16N\KOFAX16
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result11.csv  -m 1 -h-1 -s "," -W -f 65001 -S LIMSNETWORK\LIMS
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result12.csv  -m 1 -h-1 -s "," -W -f 65001 -S MathonenN\MATHONEN
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result13.csv  -m 1 -h-1 -s "," -W -f 65001 -S VMWARENET
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result14.csv  -m 1 -h-1 -s "," -W -f 65001 -S Orchestran\ORCHESTRA
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result15.csv  -m 1 -h-1 -s "," -W -f 65001 -S PWSDN1\PWSDPRD1
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result16.csv  -m 1 -h-1 -s "," -W -f 65001 -S PWSDN2\PWSDPRD2
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result18.csv  -m 1 -h-1 -s "," -W -f 65001 -S SECN\SEC
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result19.csv  -m 1 -h-1 -s "," -W -f 65001 -S SQLINTRA\SQLINTRANET
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result21.csv  -m 1 -h-1 -s "," -W -f 65001 -S PSDSQLCLU\CBO
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result22.csv  -m 1 -h-1 -s "," -W -f 65001 -S StaticWebN\STATICWEB
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result23.csv  -m 1 -h-1 -s "," -W -f 65001 -S WEBSELFCAREN\WEBSELFCARE
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result24.csv  -m 1 -h-1 -s "," -W -f 65001 -S APEXN\APEX
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result25.csv  -m 1 -h-1 -s "," -W -f 65001 -S APPDB19N\APPDB19
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result26.csv  -m 1 -h-1 -s "," -W -f 65001 -S DEDRAKDIRPROD\DEDRAKDIRPROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result27.csv  -m 1 -h-1 -s "," -W -f 65001 -S DESKTOPN19\DESKTOP19
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result28.csv  -m 1 -h-1 -s "," -W -f 65001 -S E11PRODN\E11PROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result29.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASP2016N\EGASP2016
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result30.csv  -m 1 -h-1 -s "," -W -f 65001 -S FinbudgetN\FINBUDGET
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result31.csv  -m 1 -h-1 -s "," -W -f 65001 -S GRAPROD1N\GRAPROD1
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result32.csv  -m 1 -h-1 -s "," -W -f 65001 -S GRAPROD2019N\GRAPROD2019
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result33.csv  -m 1 -h-1 -s "," -W -f 65001 -S IDAMPRODN\IDAMPROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result35.csv  -m 1 -h-1 -s "," -W -f 65001 -S RAKPOLICELIMSN\RAKPOLICELIMS
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result36.csv  -m 1 -h-1 -s "," -W -f 65001 -S SMSN\SMS
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result37.csv  -m 1 -h-1 -s "," -W -f 65001 -S TimeN\TIME
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result38.csv  -m 1 -h-1 -s "," -W -f 65001 -S TREND2019N\TRENDMICRO
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result39.csv  -m 1 -h-1 -s "," -W -f 65001 -S UCSRAKN\UCSRAK
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result40.csv  -m 1 -h-1 -s "," -W -f 65001 -S SAPGISPRDN\SAPGISPRD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result41.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGISPRODN\EGISPROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result42.csv  -m 1 -h-1 -s "," -W -f 65001 -S SGISN\SGIS
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result43.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASAPGISSTGN\EGASAPGISSTG
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result44.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGAPLSPLIMSDB
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result45.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\DEDBLSDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result46.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\OPENTEXT
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result47.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\RAKDIRECTORY
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result48.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\RAKPOLICE
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result49.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\RAKPOLICESTG
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result50.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADEDLICPDB1\DEDLICPRD1
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result51.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADEDLICPDB1\DEDLICPRD2
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result52.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADEDLICPDB1\DEDLICPRD3
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result53.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGADEDLICPDB1\DEDLICPRD4
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result54.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\AVAYACALLCENTRE
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result55.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\BAWABTIDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result56.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\CUSTOMSDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result57.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\CUSTOMSINT
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result58.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\CUSTOMSNEWDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result59.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\DBPOC
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result60.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\DEDDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result61.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\RAKGSB
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result62.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\REEM
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result63.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLDEVDB\SHAREPOINTDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result64.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLSTGDB\DMSSTG
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result65.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLSTGDB\PWSDQA
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result66.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLSTGDB\SHAREPOINTST
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result67.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLSTGDB\SHAREPOINTSTG
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result68.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLSTGDB\SPINTERNET
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result70.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTLSTGDB\ORCHESTRA
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result71.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGACNTRLDB1\REPORTSRV3
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result72.csv  -m 1 -h-1 -s "," -W -f 65001 -S SQLCENTRALASSET\ASSET
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result74.csv  -m 1 -h-1 -s "," -W -f 65001 -S SNOWN\SNOW
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result80.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\DARBDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result81.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\DARBSTAGE
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result82.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\DATACLEANSING
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result83.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\DEDLIC
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result84.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\IAMDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result85.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\IAMPROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result86.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\LICDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result87.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\LICSTAGING
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result88.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASQLCTRLDEV\RAKHH
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result92.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result93.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\CENTRIFY
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result94.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\DARB
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result95.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\EGADARBDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result96.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\EGADARBSTG
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result97.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\EGALIFETDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result98.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGAFCPDB\FORCEPOINTDB
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result99.csv  -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\SCCM
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result100.csv -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\SSPGEHR
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result101.csv -m 1 -h-1 -s "," -W -f 65001 -S EGAPCCSQL\CALLCENTER
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result102.csv -m 1 -h-1 -s "," -W -f 65001 -S EGAFINPOC
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result102.csv -m 1 -h-1 -s "," -W -f 65001 -S EGASTGDB\SSPGEHR_PROD
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result102.csv -m 1 -h-1 -s "," -W -f 65001 -S EGASCTRLDB19\E11STAGE
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result102.csv -m 1 -h-1 -s "," -W -f 65001 -S EGASCTRLDB19\RAKDIR
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result102.csv -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\DEDPORTALSTG
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result102.csv -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\KOFAXDEV2019
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result102.csv -m 1 -h-1 -s "," -W -f 65001 -S EGADCTRLDB19\ECMTUAEPASDB
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result103.csv -m 1  -h-1 -s "," -W -f 65001 -S EGADEVDB\AIRWATCH
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result104.csv -m 1  -h-1 -s "," -W -f 65001 -S EGADEVDB\BANGLOREDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result105.csv -m 1  -h-1 -s "," -W -f 65001 -S EGADEVDB\DEDBAWBATI
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result106.csv -m 1  -h-1 -s "," -W -f 65001 -S EGADEVDB\SNOW
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result107.csv -m 1  -h-1 -s "," -W -f 65001 -S EGADEVDB\ESERVICESDEV
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result108.csv -m 1  -h-1 -s "," -W -f 65001 -S EGADEVDB\INTRANETNEW
sqlcmd -E -i .\ServerDetails.sql -o .\Results\result109.csv -m 1  -h-1 -s "," -W -f 65001 -S EGADEVDB\SPINTRANETDEV
sqlcmd -U sa -P ega@1234 -i .\ServerDetails.sql -o .\Results\result17.csv -m 1  -h-1 -s "," -W -f 65001 -S EGA-SPSQLCLST
::sqlcmd -E -i .\sql2.sql -o .\Results\result2.csv   -h-1 -s "	,	" -W -f 65001 -S CSQLSERVER
::sqlcmd -E -i .\sql2.sql -o .\Results\result69.csv  -h-1 -s "	,	" -W -f 65001 -S EGADEVDB

cd .\results\ && copy result*.csv Final.csv && del result*.csv && cd ..